### ISSUE TITLE
Is the server down?

### ISSUE THREAD

**Issue by XinsongDu** [lzyacht/cmmr#1]
Greetings:

I was wondering if the server is currently down? I found I suddenly could not connect to the server (i.e., it took me infinite time to run) even when running the sample code provided in README.

Thank you!

Cheers,

**Comment by YaoxiangLi** [comment]
Please let me know if you still have the issues.

**Comment by XinsongDu** [comment]
Thanks for taking care of this @lzyacht . It works now. When I tried it before, it did not work occasionally especially on weekends.
