### ISSUE TITLE
adding columns InChIKey, SMILES and pathways to the batch search output

### ISSUE THREAD

**Issue by stolltho** [lzyacht/cmmr#4]
Hi,

I wonder if you could add columns InChIKey, SMILES and pathways to the batch search output, as this info is part of the website query output?

Cheers,
Thomas

**Comment by YaoxiangLi** [comment]
Hi Thomas,

Yes. I will check with the CEU mass mediator API and adding that part if avaliable.

Thank you,
Yaoxiang

**Comment by YaoxiangLi** [comment]
Hi @stolltho, The support for "InChIKey" and "Pathways" has been added in CMMR version > 1.0.4. However, the CEU Mass Mediator API currently returns only InChIKey and pathways, and does not include the SMILES field. As a result, we were unable to implement SMILES at this time.

Cheers,
Yaoxiang
